### PR TITLE
Support global css mixins

### PR DESCRIPTION
**Pull request by jedmao**
This PR allows you to stuff css files in your mixins dir, in which there can be any number of css mixins, defined via `@define-mixin`.

### CODE REVIEW

**Comment by TrySound** [comment]
Seems like too excessive. css mixins should be concatenated or imported, IMHO.

**Comment by ai** [comment]
@TrySound me too. But anyway it is lack in functionality.

I think we can release it.

**Comment by TrySound** [comment]
But maybe there is a way to make it async?

**Comment by TrySound** [comment]
@jedmao Can you make it async?

**Comment by jedmao** [comment]
Node's require statement isn't async, so I saw no reason to make requiring a CSS file async. It works exactly the same way the js and json files work.

**Comment by TrySound** [comment]
@jedmao You use readFileSync. It's not require. Provide async version please. U can make something like this
```
return Promise.all([globby(...).then(function () { ... }), requireCss(...)]).then(function () { define/insert });
```

**Comment by TrySound** [comment]
@jedmao Also I provide js/json files asynchronically with promises.

**Comment by TrySound** [comment]
@jedmao Sorry, I got confused. But I still think we should use async separately for css files .

**Comment by TrySound** [comment]
@jedmao `require` can be optimized by node. But sync fs functions can make application slower, caz it dinamical operation. Or something like this.

**Comment by jedmao** [comment]
@TrySound what if you have multiple mixins defined with the same name? If it's async it has the potential to sometimes be the first one and sometimes the last, right?

**Comment by jedmao** [comment]
Granted, having multiple mixins with the same name is ASKING for trouble, but still.

**Pull request merged**
