### PR TITLE
add mixinsText option

### LINKED ISSUE #95: Sync API
It would be super useful to run this plugin in sync mode. many editor related plugins choke on async plugins

### PR DESCRIPTION
**Pull request by hipstersmoothie**
I need the ability to run this plugin synchronously. This PR add an option to pass all your mixins as the actually CSS text. This enable you to load whatever you want synchronously so postcss can stay sync

closes #95

### CODE REVIEW

**Comment by ai** [comment]
What is your use case? Maybe we can find better API for it.

**Comment by hipstersmoothie** [comment]
@ai 

1. as a typescript language service plugin (they can't be async) https://github.com/mrmckeb/typescript-plugin-css-modules
2. as a typescript compiler plugin (writing this internally at my company) where again all my postcss plugins must load synchronously

**Comment by hipstersmoothie** [comment]
I tried just adding a `sync` option but it required a lot of code changes that I feel wouldn't be accepted from an outside contributor.  All the file loading is so Promise based I would've had to move a lot of code. This seemed like the easiest alternative

**Comment by ai** [comment]
Why `mixins` option is not a solution here? You can pass a custom sync function.

**Comment by hipstersmoothie** [comment]
I already have all my mixins in css files and I was under the impression that the `mixins` option you had to use the postcss API to creating the mixins manually.

Is there a way to just pass a string to `mixins`?

**Comment by ai** [comment]
You can create function, which will take string, parse it and create `mixins` object with functions.

I think it will be the best option, since it doesn't add new options, which we will need to support in the future.

**Comment by hipstersmoothie** [comment]
> which will take string, parse it and create mixins object with functions 

I am not sure how to convert the string to the mixins object....

```js
const mixinsPlugin = require('postcss-mixins');
const fs = require('fs');
const postcss = require('postcss');

const elevation = fs.readFileSync(
  require.resolve('@cgds/styles/elevation.css'),
  'utf8'
);

function makeMixinDefinition(file) {
  return {};
}

module.exports = () => {
  return {
    plugins: [mixinsPlugin({ mixinsFiles: makeMixinDefinition(elevation) })]
  };
};
```

**Pull request closed without merging**
