### PR TITLE
Enable hot reloading of the functional mixins

### PR DESCRIPTION
**Pull request by andgra**
Hello,

In additional to the #145 I added `try ... catch` around `require` of mixin file. In case there is a syntax of any other error in a single mixin file, other mixins will be loaded successfully. Should I write tests for this case?

### CODE REVIEW

**Comment by ai** [comment]
No, we do not need tests for errors

**Comment by ai** [comment]
I fixed CI. Do you plan to send another PR or we are ready for release?

**Comment by andgra** [comment]
Actually, there is an issue with windows OS. While mixinsDir option is sanitized for the glob package (replace `\` with `/`), mixinsFiles are not.
So paths like `mixinsFiles: join(__dirname, 'deps', 'f.js')` will always fail on windows.
There is an easy way to fix this, but I didn't include it in current PR because its a different issue

**Comment by andgra** [comment]
P.S. also there is an issue with `.CSS` files on windows when we use `mixinsDir` (file extension in upper case), but its very rare case and I dont know how to easily fix it. But if your file extensions always in lower case, there is no issue at all.

**Comment by ai** [comment]
Thanks for the great research on Windows compatibility. I will wait for PRs.

**Comment by andgra** [comment]
Created #147

**Comment by ai** [comment]
Thanks. Released in 9.0.3.

**Pull request merged**
