### PR TITLE
Async CSS mixin import

### PR DESCRIPTION
**Pull request by jedmao**
As requested by @TrySound in https://github.com/postcss/postcss-mixins/pull/29#issuecomment-148805487

### CODE REVIEW

**Comment by TrySound** [comment]
@jedmao Cool! But can you remove promise dependency? If somebody need to use postcss on old node, they can use polyfills.

**Comment by jedmao** [comment]
@TrySound done.

**Comment by TrySound** [comment]
@jedmao Also you can return Promise.all result and add .then() one scope above

**Comment by jedmao** [comment]
@TrySound I could, but I didn't think that was as readable.

**Comment by TrySound** [comment]
@jedmao One extra variable, more idents. Not so readable. We like less scopes :)

**Comment by TrySound** [comment]
@jedmao Or it looks like callback hell

**Comment by jedmao** [comment]
@TrySound maybe I don't understand your strategy then, because I don't see a way to reduce the nesting the way it is now.

**Comment by TrySound** [comment]
@jedmao 
```js
new Promise(function (resolve) {
  resolve()
}).then(function () {
  return new Promise(function (resolve) {
    resolve()
  });
}).then(function () {
  return new Promise(function (resolve) {
    resolve()
  });
})
```

**Comment by jedmao** [comment]
@TrySound there you go.

**Comment by TrySound** [comment]
@jedmao Globby already return promise instance. We don't need to wrap it.

**Comment by jedmao** [comment]
@TrySound done.

**Comment by jedmao** [comment]
@TrySound I'm now doing `return reject(err);`

**Comment by TrySound** [comment]
@jedmao Cool, thanks.
@ai Now looks good to merge.

**Comment by jedmao** [comment]
@ai ping

**Comment by ai** [comment]
Oops :)

**Comment by ai** [comment]
Released in 2.1.1.

**Pull request merged**
